name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Esta etapa lista os arquivos para vermos onde o package.json realmente está
      - name: List files
        run: ls -R 

      - name: Install and Build
        # Este comando entra na subpasta correta e roda o build
        run: |
          cd Dashboard-skeleton-design
          npm install
          npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Aponta para a pasta dist dentro da subpasta correta
          path: './Dashboard-skeleton-design/dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
